using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Engine.Models;

namespace Engine.Factories
{
    internal class UpdateFactory
    {
        internal Updates CreateUpdate()
        {
            Updates newUpdate = new Updates();
            newUpdate.AddDailyUpdate("New York City", 1, "New York has had 600 cases and its first 2 deaths. The United States has surpassed 50 deaths. President Trump has tested negative.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("New York City", 2, "New York has had 700 cases. Italy has surpassed 1,800 deaths. The C.D.C. advised no gatherings of 50 or more people.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("New York City", 3, "New York has had 900 cases. Italy has surpassed 25,000 cases.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("New York City", 4, "New York has had 1,000 cases and 10 deaths. All 62 counties in New York have declared a state of emergency. Schools, bars, and restaurants will be closed, except for food takeout and delivery.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("New York City", 5, "New York has had 2,000 cases. The U.S. has closed its borders to non-esssential traveling. President Trump has signed into a COVID-19 relief package which includes free testing and paid emergency leave.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("New York City", 6, "New York has had 4,000 cases. China has reported no COVID-19 cases for the first time since the pandemic began. Italy now has the most COVID-19 related deaths at 3,405.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("New York City", 7, "New York has had 5,000 cases. President Trump has declared a major emergency in New York and requested for federal assistance to be given. Spain has nearly 20,000 cases.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("New York City", 8, "New York has had 10,000 cases and 50 deaths. Mayor de Blasio said New York City is the epicenter of the COVID-19 pandemic in the U.S.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("New York City", 9, "New York has had 900 cases. Italy has surpassed 25,000 cases.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("New York City", 10, "Governor Andrew Cuomo has issued a stay at home order to all New Yorkers. Senator Rand Paul has become the first senator to test positive. Italy has surpassed 50,000 cases.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("New York City", 11, "New York has had 20,000 cases and 100 deaths. Iran has surpassed 20,000 cases. Globally, there have been more than 300,000 cases.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("New York City", 12, "The United States has surpassed 50,000 cases. Chinese authorities have stated that travel restrictions in Wuahn will be lifted on 4/8", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("New York City", 13, "New York has had 30,000 cases. The White House and Senate have agreed upon a $2 trillion stimulus deal to help lessen the economic damage of COVID-19. Spain now has the second-highest death toll at 3,434.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("New York City", 14, "USNS Comfort, a hospital ship of the United States Navy, is heading to New York City to assist hospitals.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("New York City", 15, "New York has had 40,000 cases and 500 deaths. Globally, there have been more than 500,000 cases. The United States have surpassed Italy and China with most confirmed cases at more than 86,000. President Trump signs the stimulus package into law.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("New York City", 16, "Italy has surpassed 10,000 deaths. South Korea has reported more recoveries than active COVID-19 cases for the first time since the start of the outbreak. New York’s 2020 Democratic Primary will be postponed until 6/23.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("New York City", 17, "New York has had 900 deaths.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("New York City", 18, "New York has had 60,000 cases and 1,000 deaths. USNS Comfort has arrived in New York City. The Tokyo 2020 Olympic Games have been postponed to 2021.", "/Engine;component/Images/Map/map_11.png");
            newUpdate.AddDailyUpdate("New York City", 19, "New York has had 70,000 cases. The death toll in the United States has surpassed China's with more than 4,000 in more than 3000,000 cases. A child has died in New York City for the first time.", "/Engine;component/Images/Map/map_11.png");
            newUpdate.AddDailyUpdate("New York City", 20, "New York has had 80,000 cases. A 6-week-old baby, the youngest victim to date, has died due to COVID-19.", "/Engine;component/Images/Map/map_11.png");
            newUpdate.AddDailyUpdate("New York City", 21, "New York has had 90,000 cases and 2,000 deaths. Globally, there have been more than 1 million cases. Spain has surpasssed 10,000 deaths.", "/Engine;component/Images/Map/map_12.png");
            newUpdate.AddDailyUpdate("New York City", 22, "New York has had 1000,000 cases. The Trump Administration is recommending that Americans wear non-medical cloth face coverings.", "/Engine;component/Images/Map/map_13.png");
            newUpdate.AddDailyUpdate("New York City", 23, "New York has had 110,000 cases and 3,000 deaths.", "/Engine;component/Images/Map/map_13.png");
            newUpdate.AddDailyUpdate("New York City", 24, "New York has had 120,000 cases and 4,000 deaths. President Trump stated that he believes everything will be alright in the end in a press briefing.", "/Engine;component/Images/Map/map_14.png");
            newUpdate.AddDailyUpdate("New York City", 25, "New York has had 130,000 cases.", "/Engine;component/Images/Map/map_14.png");
            newUpdate.AddDailyUpdate("New York City", 26, "New York has had 5,000 deaths. 42 states have issued stay at home orders. President Trump stated that there will be 110,000 ventilators issued to states by June.", "/Engine;component/Images/Map/map_14.png");
            newUpdate.AddDailyUpdate("New York City", 27, "New York has had 150,000 cases and 6,000 deaths. Globally, there have been more than 1.5 million cases and 80,000 deaths.", "/Engine;component/Images/Map/map_15.png");
            newUpdate.AddDailyUpdate("New York City", 28, "New York has had 160,000 cases and 7,000 deaths.", "/Engine;component/Images/Map/map_15.png");
            newUpdate.AddDailyUpdate("New York City", 29, "New York has had 170,000 cases. New York has more cases than any non-United States country.", "/Engine;component/Images/Map/map_16.png");
            newUpdate.AddDailyUpdate("New York City", 30, "New York has had 180,000 cases and 8,000 deaths.", "/Engine;component/Images/Map/map_16.png");
            newUpdate.AddDailyUpdate("New York City", 31, "Today is Easter.", "/Engine;component/Images/Map/map_16.png");
            newUpdate.AddDailyUpdate("New York City", 32, "New York has had 190,000 cases.", "/Engine;component/Images/Map/map_17.png");
            newUpdate.AddDailyUpdate("New York City", 33, "Governor Cuomo has asked that people stay calm and keep on social distancing.", "/Engine;component/Images/Map/map_17.png");
            newUpdate.AddDailyUpdate("New York City", 34, "New York has had 200,000 cases.", "/Engine;component/Images/Map/map_18.png");
            newUpdate.AddDailyUpdate("New York City", 35, "New York has had 210,000 cases.", "/Engine;component/Images/Map/map_19.png");
            newUpdate.AddDailyUpdate("New York City", 36, "New York has had 220,000 cases.", "/Engine;component/Images/Map/map_20.png");
            newUpdate.AddDailyUpdate("New York City", 37, "New York has had 230,000 cases.", "/Engine;component/Images/Map/map_20.png");

            newUpdate.AddDailyUpdate("London", 1, "The UK has had 200 cases and 3 deaths.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("London", 2, "The UK has had 300 cases and 5 deaths.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("London", 3, "Mental health minister MP Madine Dorries has tested positive. The W.H.O. has declared the COVID-19 outbreak a pandemic.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("London", 4, "The UK has had 400 cases.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("London", 5, "The UK has had 500 cases and 10 deaths. The government has asked that anyone with a continuous cough or fever should self-isolate for a week. Schools have canceled any trips abroad.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("London", 6, "The UK has had 800 cases. Many sporting events have been postponed or cancelled.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("London", 7, "The UK has had 1,000 cases and 20 deaths.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("London", 8, "Italy has surpassed 1,800 deaths. Anyone over 70 in Britain has been told to self-isolate within the coming weeks.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("London", 9, "The UK has had 1,500 cases and 50 deaths. Italy has surpassed 25,000 cases.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("London", 10, "All non-urgent operations in England have been postponed from 4/15 in order to free up 30,000 beds. A £3.2million emergency support package has been provided by the government.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("London", 11, "The UK has had 2,000 cases and 100 deaths. MP Lloyd Russell-Moyle has tested positive. The Ministry of Defence has announced that a COVID Support Force consisting of 20,000 troops will assist public services.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("London", 12, "The UK has had 3,000 cases. China has reported no COVID-19 cases for the first time since the pandemic began. Italy now has the highest death toll at 3,405.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("London", 13, "Spain has nearly 20,000 cases.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("London", 14, "The UK has had 5,000 cases and 200 deaths. Italy has surpassed 50,000 cases.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("London", 15, "A group of NHS (National Health Service) workers in the UK had requested that more protection equipment is provided.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("London", 16, "The UK has had 6,000 cases. Prime Minister Boris Johnson has issued a stay at home order to those in the UK. Iran has surpassed 20,000 cases. Globally, there have been more than 300,000 cases.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("London", 17, "The UK has had 8,000 cases. A temporary critical care hospital in London called the NHS Nightingale Hospital has been set up. Chinese authorities have stated that travel restrictions in Wuahn will be lifted on 4/8.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("London", 18, "The UK has had 500 deaths. British diplomant Steven Dick, deputy ambassador to Hungary, died from COVID-19.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("London", 19, "The UK has had 10,000 cases. Prince Charles has tested positive. Spain now has the second-highest death toll at 3,434.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("London", 20, "The UK has had 1,000 deaths. Globally, there have been more than 500,000 cases. The United States have surpassed Italy and China with most confirmed cases at more than 86,000. Prime Minister Boris Johnson has tested positive.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("London", 21, "The UK has had 15,000 cases. Italy has surpassed 10,000 deaths. South Korea has reported more recoveries than active COVID-19 cases for the first time since the start of the outbreak.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("London", 22, "A warning letter has been sent to each household with a health info and government restrictions leaflet attached.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("London", 23, "The UK has had 20,000 cases and 1,500 deaths. The Tokyo 2020 Olympic Games have been postponed to 2021.", "/Engine;component/Images/Map/map_11.png");
            newUpdate.AddDailyUpdate("London", 24, "The UK has had 25,000 cases and 2,000 deaths.", "/Engine;component/Images/Map/map_11.png");
            newUpdate.AddDailyUpdate("London", 25, "A 6-week-old baby, the youngest victim to date, has died due to COVID-19. It has been confirmed that the 2,000 NHS staff has been tested.", "/Engine;component/Images/Map/map_11.png");
            newUpdate.AddDailyUpdate("London", 26, "The UK has had 30,000 cases and 3,000 deaths. Globally, there have been more than 1 million cases. Spain has surpassed 10,000 deaths. Health Secretary Matt Hancock announced his goal of doing 1000,000 daily by the end of April.", "/Engine;component/Images/Map/map_12.png");
            newUpdate.AddDailyUpdate("London", 27, "The UK has had 4,000 deaths.", "/Engine;component/Images/Map/map_13.png");
            newUpdate.AddDailyUpdate("London", 28, "The UK has had 40,000 cases. A five-year-old has died due to COVID-19.", "/Engine;component/Images/Map/map_13.png");
            newUpdate.AddDailyUpdate("London", 29, "The UK has had 5,000 deaths. Queen Elizabeth II made a rare royal address about the COVID-19 pandemic to the UK and Commonwealth.", "/Engine;component/Images/Map/map_14.png");
            newUpdate.AddDailyUpdate("London", 30, "The UK has had 50,000 cases and 6,000 deaths. Prime Minister Boris Johnson has been moved to intensive care.", "/Engine;component/Images/Map/map_14.png");
            newUpdate.AddDailyUpdate("London", 31, "The UK has had 7,000 deaths. British officals have requested ventilators from the White House. President Trump said that he will help them as they have been good partners.", "/Engine;component/Images/Map/map_14.png");
            newUpdate.AddDailyUpdate("London", 32, "The UK has had 60,000 cases. Globally, there have been more than 1.5 million cases and 80,000 deaths. The EU plans to prolong the non-essential travel ban until May 15.", "/Engine;component/Images/Map/map_15.png");
            newUpdate.AddDailyUpdate("London", 33, "The UK has had 8,000 deaths. UK citizens have been urged to stay indoors over Easter weekend.", "/Engine; component/Images/Map/map_15.png");
            newUpdate.AddDailyUpdate("London", 34, "The UK has had 70,000 cases and 9,000 deaths.", "/Engine;component/Images/Map/map_16.png");
            newUpdate.AddDailyUpdate("London", 35, "The UK has had 10,000 deaths. The Queen has released an Easter message for the first time wherein she described her hopes to win against the pandemic.", "/Engine;component/Images/Map/map_16.png");
            newUpdate.AddDailyUpdate("London", 36, "The UK has had 80,000 cases and 10,000 deaths. Today is Easter.", "/Engine;component/Images/Map/map_16.png");
            newUpdate.AddDailyUpdate("London", 37, "The UK has had 11,000 deaths.", "/Engine;component/Images/Map/map_17.png");
            newUpdate.AddDailyUpdate("London", 38, "The UK has had 90,000 cases.", "/Engine;component/Images/Map/map_17.png");
            newUpdate.AddDailyUpdate("London", 39, "The UK has had 12,000 deaths.", "/Engine;component/Images/Map/map_18.png");
            newUpdate.AddDailyUpdate("London", 40, "The UK has had 100,000 cases and 13,000 deaths.", "/Engine;component/Images/Map/map_19.png");
            newUpdate.AddDailyUpdate("London", 41, "The UK has had 14,000 deaths.", "/Engine;component/Images/Map/map_20.png");
            newUpdate.AddDailyUpdate("London", 42, "The UK has had 110,000 cases.", "/Engine;component/Images/Map/map_20.png");
            newUpdate.AddDailyUpdate("London", 43, "The UK has had 15,000 deaths.", "/Engine;component/Images/Map/map_20.png");
            newUpdate.AddDailyUpdate("London", 44, "The UK has had 120,000 cases.", "/Engine;component/Images/Map/map_20.png");
            newUpdate.AddDailyUpdate("London", 45, "The UK has had 16,000 deaths.", "/Engine;component/Images/Map/map_20.png");

            newUpdate.AddDailyUpdate("Wuhan", 1, "China has had 41 cases and its first death.", "/Engine;component/Images/Map/map_01.png");
            newUpdate.AddDailyUpdate("Wuhan", 2, "Japan has had its first case.", "/Engine;component/Images/Map/map_01.png");
            newUpdate.AddDailyUpdate("Wuhan", 3, "China has had 50 cases and 2 deaths.", "/Engine;component/Images/Map/map_01.png");
            newUpdate.AddDailyUpdate("Wuhan", 4, "China has had 100 cases. Today is the Annual Wuhan Lunar New Year banquet, which over 40,000 families have taken part in.", "/Engine;component/Images/Map/map_01.png");
            newUpdate.AddDailyUpdate("Wuhan", 5, "The first case has been reported in China outside of Wuhan.", "/Engine;component/Images/Map/map_01.png");
            newUpdate.AddDailyUpdate("Wuhan", 6, "China has had 200 cases. South Korea has had its first case. Zong Nanshan, a Chinese doctoer, has announced that the virus is spread between people.", "/Engine;component/Images/Map/map_01.png");
            newUpdate.AddDailyUpdate("Wuhan", 7, "China has had 400 cases. The United States has had its first case.", "/Engine;component/Images/Map/map_01.png");
            newUpdate.AddDailyUpdate("Wuhan", 8, "China has had 500 cases and 10 deaths.", "/Engine;component/Images/Map/map_02.png");
            newUpdate.AddDailyUpdate("Wuhan", 9, "China has had 800 cases and 20 deaths. Wuhan has gone into quarantine: planes and trains cannot leave the city, and buses, subways, and ferries have been suspended.", "/Engine;component/Images/Map/map_01.png");
            newUpdate.AddDailyUpdate("Wuhan", 10, "China has had 1,000 cases. Today is the start of the Lunar New Year holiday. China has extended the lockdown to over 36 million and a new hospital is starting to be built in Wuhan.", "/Engine;component/Images/Map/map_01.png");
            newUpdate.AddDailyUpdate("Wuhan", 11, "China has had 50 deaths. Chinese President Xi Jinping stated that the speed of the coronavirus is grave.", "/Engine;component/Images/Map/map_02.png");
            newUpdate.AddDailyUpdate("Wuhan", 12, "China has had 2,000 cases.", "/Engine;component/Images/Map/map_02.png");
            newUpdate.AddDailyUpdate("Wuhan", 13, "China has had 4,000 cases and 100 deaths.", "/Engine;component/Images/Map/map_02.png");
            newUpdate.AddDailyUpdate("Wuhan", 14, "China has had 5,000 cases.", "/Engine;component/Images/Map/map_02.png");
            newUpdate.AddDailyUpdate("Wuhan", 15, "China has had 7,000 cases.", "/Engine;component/Images/Map/map_02.png");
            newUpdate.AddDailyUpdate("Wuhan", 16, "China has had 9,000 cases and 200 deaths. The W.H.O. has declared a global health emergency.", "/Engine;component/Images/Map/map_03.png");
            newUpdate.AddDailyUpdate("Wuhan", 17, "China has had 10,000 cases and 300 deaths.", "/Engine;component/Images/Map/map_03.png");
            newUpdate.AddDailyUpdate("Wuhan", 18, "There has been a death outside of Mainland China.", "/Engine;component/Images/Map/map_03.png");
            newUpdate.AddDailyUpdate("Wuhan", 19, "China has had 20,000 cases and 400 deaths.", "/Engine;component/Images/Map/map_03.png");
            newUpdate.AddDailyUpdate("Wuhan", 20, "The W.H.O. released Novel coronaviru Donor Alert, which is a document that outlines the strategy to combat the virus and assesses its risk.", "/Engine;component/Images/Map/map_03.png");
            newUpdate.AddDailyUpdate("Wuhan", 21, "China has had 500 deaths. The Diamond Princess cruise ship is quarantined. Chinese experts had stated that nucleic acid testing is only able to identify 30%-50% positive cases.", "/Engine;component/Images/Map/map_04.png");
            newUpdate.AddDailyUpdate("Wuhan", 22, "China has had 30,000 cases and 600 deaths.", "/Engine;component/Images/Map/map_04.png");
            newUpdate.AddDailyUpdate("Wuhan", 23, "China has had 700 deaths. Dr. Li Wenliang, the Chinese whistleblower who warned about COVID-19, has died after being infected.", "/Engine;component/Images/Map/map_04.png");
            newUpdate.AddDailyUpdate("Wuhan", 24, "China has had 800 deaths.", "/Engine;component/Images/Map/map_04.png");
            newUpdate.AddDailyUpdate("Wuhan", 25, "China has had 40,000 cases and 900 deaths. The death toll has surpassed the count from the SARS epidemic, which had 811 deaths.", "/Engine;component/Images/Map/map_05.png");
            newUpdate.AddDailyUpdate("Wuhan", 26, "China has had 1,000 deaths.", "/Engine;component/Images/Map/map_05.png");
            newUpdate.AddDailyUpdate("Wuhan", 27, "Globally, there have been more than 1,000 deaths.", "/Engine;component/Images/Map/map_05.png");
            newUpdate.AddDailyUpdate("Wuhan", 28, "China has had 50,000 cases.", "/Engine;component/Images/Map/map_05.png");
            newUpdate.AddDailyUpdate("Wuhan", 29, "China has had 60,000 cases. Wuhan has put in place an order forbidding people from leaving neighborhoods for non-medical reasons.", "/Engine;component/Images/Map/map_05.png");
            newUpdate.AddDailyUpdate("Wuhan", 30, "Africa has had its first case.", "/Engine;component/Images/Map/map_05.png");
            newUpdate.AddDailyUpdate("Wuhan", 31, "The United States announced that they would evacuate American citizens currently on the Diamond Princess.", "/Engine;component/Images/Map/map_05.png");
            newUpdate.AddDailyUpdate("Wuhan", 32, "Globally, there have been more than 70,000 cases. Tawain has had its first death.", "/Engine;component/Images/Map/map_05.png");
            newUpdate.AddDailyUpdate("Wuhan", 33, "American citizens evacuated the Diamond Princess and will quarantine themselves for 2 weeks in the United States.", "/Engine;component/Images/Map/map_06.png");
            newUpdate.AddDailyUpdate("Wuhan", 34, "President Xi Jinpin said in a phone call with Britsh Prime Minister Boris Johnson that China is achieving visible progress.", "/Engine;component/Images/Map/map_06.png");
            newUpdate.AddDailyUpdate("Wuhan", 35, "Globally, there have been more than 2,000 deaths. An outbreak has began in Iran.", "/Engine;component/Images/Map/map_06.png");
            newUpdate.AddDailyUpdate("Wuhan", 36, "Wuahn residents must meausre their temperature twice daily and report any temperatures higher than 99.1 °F (37.3 °C).", "/Engine;component/Images/Map/map_06.png");
            newUpdate.AddDailyUpdate("Wuhan", 37, "An outbreak has began in Italy.", "/Engine;component/Images/Map/map_07.png");
            newUpdate.AddDailyUpdate("Wuhan", 38, "Wuhan requires that any patients discharged from COVID-19 quarantine themselves for 2 weeks.", "/Engine;component/Images/Map/map_07.png");
            newUpdate.AddDailyUpdate("Wuhan", 39, "President Xi Jinping has reassured officals that the Chinese government will prevail against COVID-19. Turkey and Afghanistan have closed borders to Iran.", "/Engine;component/Images/Map/map_07.png");
            newUpdate.AddDailyUpdate("Wuhan", 40, "China has had 70,000 cases. Cases have spiked in Italy, making it the hardest hit country in Europe.", "/Engine;component/Images/Map/map_07.png");
            newUpdate.AddDailyUpdate("Wuhan", 41, "North Korea has 380 foreigners under quarantine for 30 days.", "/Engine;component/Images/Map/map_07.png");
            newUpdate.AddDailyUpdate("Wuhan", 42, "The United States has had its first death. Latin America has had its first death.", "/Engine;component/Images/Map/map_07.png");
            newUpdate.AddDailyUpdate("Wuhan", 43, "The W.H.O. urged that countries protect themselves against COVID-19 and to not believe that they will be spared.", "/Engine;component/Images/Map/map_07.png");
            newUpdate.AddDailyUpdate("Wuhan", 44, "Iran has reported 34 deaths out of 388 confirmed cases, which makes it the 2nd country with the highest amount of deaths.", "/Engine;component/Images/Map/map_07.png");
            newUpdate.AddDailyUpdate("Wuhan", 45, "There has been a death in the United States for the first time.", "/Engine;component/Images/Map/map_08.png");

            newUpdate.AddDailyUpdate("Los Angeles", 1, "Los Angeles has had 20 cases and its first death.", "/Engine;component/Images/Map/map_08.png");
            newUpdate.AddDailyUpdate("Los Angeles", 2, "Former President Barack Obama has requested online that people look out for one another.", "/Engine;component/Images/Map/map_08.png");
            newUpdate.AddDailyUpdate("Los Angeles", 3, "President Trump has declared a national emergency.", "/Engine;component/Images/Map/map_08.png");
            newUpdate.AddDailyUpdate("Los Angeles", 4, "The United States has surpassed 50 deaths. President Trump has tested negative.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("Los Angeles", 5, "Los Angeles has had 50 cases. Italy has surpassed 1,800 deaths. The C.D.C. advised no gatherings of 50 or more people.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("Los Angeles", 6, "Los Angeles County has closed bars, gyms, movie theaters, and schools. Italy has surpassed 25,000 cases.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("Los Angeles", 7, "Los Angeles has had 100 cases. Courts have closed.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("Los Angeles", 8, "Los Angeles has had 200 cases. The U.S. has closed its borders to non-esssential traveling. President Trump has signed into a COVID-19 relief package which includes free testing and paid emergency leave.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("Los Angeles", 9, "China has reported no COVID-19 cases for the first time since the pandemic began. Italy now has the most COVID-19 related deaths at 3,405.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("Los Angeles", 10, "Spain has nearly 20,000 cases.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("Los Angeles", 11, "Los Angeles has had 300 cases. Italy has surpassed 50,000 cases.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("Los Angeles", 12, "Los Angeles has had 400 cases and 5 deaths. New York City has surpased 10,000 cases. Senator Rand Paul has become the first senator to test positive.", "/Engine;component/Images/Map/map_09.png");
            newUpdate.AddDailyUpdate("Los Angeles", 13, "Los Angeles has had 500 cases. Iran has surpassed 20,000 cases. Globally, there have been more than 300,000 cases.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("Los Angeles", 14, "Los Angeles has had 600 cases and 10 deaths. The United States has surpassed 50,000 cases. Chinese authorities have stated that travel restrictions in Wuahn will be lifted on 4/8.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("Los Angeles", 15, "Los Angeles has had 800 cases. The White House and Senate have agreed upon a $2 trillion stimulus deal to help lessen the economic damage of COVID-19. Spain now has the second-highest death toll at 3,434.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("Los Angeles", 16, "Los Angeles has had 1,000 cases and 20 deaths. California has surpassed 3,000 cases. Gun stores have been closed in 42 cities.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("Los Angeles", 17, "The United States have surpassed Italy and China with most confirmed cases at more than 86,000. Globally, there have been more than 500,000 cases.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("Los Angeles", 18, "Italy has surpassed 10,000 deaths. South Korea has reported more recoveries than active COVID-19 cases for the first time since the start of the outbreak.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("Los Angeles", 19, "Los Angeles has had 2,000 cases.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("Los Angeles", 20, "Farmer’s markets have closed. The Tokyo 2020 Olympic Games have been postponed to 2021.", "/Engine;component/Images/Map/map_10.png");
            newUpdate.AddDailyUpdate("Los Angeles", 21, "Los Angeles has had 3,000 cases and 50 deaths.", "/Engine;component/Images/Map/map_11.png");
            newUpdate.AddDailyUpdate("Los Angeles", 22, "A 6-week-old baby, the youngest victim to date, has died due to COVID-19.", "/Engine;component/Images/Map/map_11.png");
            newUpdate.AddDailyUpdate("Los Angeles", 23, "Globally, there have been more than 1 million cases. Spain has surpassed 10,000 deaths.", "/Engine;component/Images/Map/map_11.png");
            newUpdate.AddDailyUpdate("Los Angeles", 24, "The Trump Administration is recommending that Americans wear non-medical cloth face coverings.", "/Engine;component/Images/Map/map_12.png");
            newUpdate.AddDailyUpdate("Los Angeles", 25, "Los Angeles has had 100 deaths. New York has had 100 deaths.", "/Engine;component/Images/Map/map_13.png");
            newUpdate.AddDailyUpdate("Los Angeles", 26, "President Trump stated that he believes everything will be alright in the end in a press briefing.", "/Engine;component/Images/Map/map_13.png");
            newUpdate.AddDailyUpdate("Los Angeles", 27, "All Los Angeles County residents are eligible for COVID-19 testing.", "/Engine;component/Images/Map/map_14.png");
            newUpdate.AddDailyUpdate("Los Angeles", 28, "42 states have issued stay at home orders. President Trump stated that there will be 110,000 ventilators issued to states by June.", "/Engine;component/Images/Map/map_14.png");
            newUpdate.AddDailyUpdate("Los Angeles", 29, "", "/Engine;component/Images/Map/map_14.png");
            newUpdate.AddDailyUpdate("Los Angeles", 30, "Los Angeles has had 7,000 cases. Globally, there have been more than 1.5 million cases and 80,000 deaths. California has a $1.4 billion plan to buy medical equipment.", "/Engine;component/Images/Map/map_15.png");
            newUpdate.AddDailyUpdate("Los Angeles", 31, "", "/Engine;component/Images/Map/map_15.png");
            newUpdate.AddDailyUpdate("Los Angeles", 31, "Los Angeles has had 8,000 cases. Los Angeles County has extended its stay at home order until 5/15.", "/Engine;component/Images/Map/map_16.png");
            newUpdate.AddDailyUpdate("Los Angeles", 32, "County Offical say to keep social distancing over Easter.", "/Engine;component/Images/Map/map_16.png");
            newUpdate.AddDailyUpdate("Los Angeles", 33, "Los Angeles has had 9,000 cases. Today is Easter.", "/Engine;component/Images/Map/map_16.png");
            newUpdate.AddDailyUpdate("Los Angeles", 34, "Los Angeles has had 300 deaths.", "/Engine;component/Images/Map/map_17.png");
            newUpdate.AddDailyUpdate("Los Angeles", 35, "Los Angeles has had 10,000 cases.", "/Engine;component/Images/Map/map_17.png");
            newUpdate.AddDailyUpdate("Los Angeles", 36, "Governor Newsom has resassured Californians that things will work out.", "/Engine;component/Images/Map/map_18.png");
            newUpdate.AddDailyUpdate("Los Angeles", 37, "Los Angeles has had 11,000 cases.", "/Engine;component/Images/Map/map_19.png");
            newUpdate.AddDailyUpdate("Los Angeles", 38, "Los Angeles has had 400 deaths.", "/Engine;component/Images/Map/map_20.png");
            newUpdate.AddDailyUpdate("Los Angeles", 39, "Los Angeles has had 12,000 cases.", "/Engine;component/Images/Map/map_20.png");
            newUpdate.AddDailyUpdate("Los Angeles", 40, "", "/Engine;component/Images/Map/map_20.png");
            newUpdate.AddDailyUpdate("Los Angeles", 41, "Los Angeles has had 13,000 cases.", "/Engine;component/Images/Map/map_20.png");
            newUpdate.AddDailyUpdate("Los Angeles", 42, "", "/Engine;component/Images/Map/map_20.png");

            return newUpdate;


        }
    }
}
